name: 'Setup Python Environment'
description: 'Sets up Python environment with dependencies using Conda'

runs:
  using: "composite"
  steps:
    - name: Install Miniconda
      shell: bash
      run: |
        apt-get update
        apt-get install -y wget
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source $HOME/miniconda/bin/activate
        conda init bash

    - name: Create and activate environment
      shell: bash
      run: |
        source $HOME/miniconda/bin/activate
        conda env create -f environment.yml
        conda activate myenv  # Replace 'myenv' with your environment name from environment.yml

    - name: Install Poetry
      shell: bash
      run: |
        conda install -c conda-forge poetry
        poetry install
