name: 'Setup Python Environment'
description: 'Sets up Python environment with dependencies using Conda'

runs:
  using: "composite"
  steps:
    - name: Install Miniconda
      shell: bash
      run: |
        apt-get -qq update
        apt-get -qq install -y wget
        mkdir -p ~/miniconda3
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
        rm ~/miniconda3/miniconda.sh

    - name: Create and activate environment
      shell: bash
      run: |
        conda env create -n python_env python=3.13
        conda activate python_env

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
