load_clean:
  input_path: data/raw_data/customers.csv
  output_path: data/cleaned/clean_customers.pqt

feature:
  column_name: first_name
  output_path: data/features/customers_feature.pqt
  obj_path: data/obj/customers_feature.pkl

train_model:
  output_path: data/predictions/predictions.pqt
  obj_path: data/obj/constant_model.pkl
  constant: 42.0

inference:
  inference_data_path: data/raw_data/test_data.csv
  y_data_path: data/raw_data/y_data.csv
  output_path: data/inference/inference.pqt
  obj_path: data/obj/inference.pkl
