load_clean:
  input_path: data/raw_data/customers.csv
  output_path: data/cleaned/clean_customers.pqt

feature:
  column_name: first_name
  output_path: data/features/customers_feature.pqt
  obj_path: data/obj/customers_feature.pkl

train_model:
  output_path: data/predictions/predictions.pqt
  model_path: data/obj/constant_model.pkl
  constant: 42.0
