name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t app .
    - name: Run linters
      run: |
        docker run app bash -c "
        source ~/.bashrc && \
        conda activate python_env && \
        poetry run flake8 . && \
        poetry run black --check . && \
        poetry run isort --check-only ."

  tests:
    runs-on: ubuntu-latest
    needs: linters
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t app .
    - name: Run tests
      run: |
        docker run app bash -c "
        source ~/.bashrc && \
        conda activate python_env && \
        poetry run pytest tests/"
