name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: python:3.13-slim

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          python -m pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Run Ruff
        run: ruff check .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: python:3.13-slim

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          python -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: pytest
