name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    container:
      image: python:3.13-slim
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Print pyproject.toml
        run: cat pyproject.toml
      - name: Run Ruff
        run: ruff check .
      - name: Run Mypy
        run: mypy .

  test:
    name: Run Tests
    runs-on: self-hosted
    container:
      image: python:3.13-slim
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run pytest
        run: pytest
